//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoGo.DiscordBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PoGo.DiscordBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds a role to the user.
        /// </summary>
        public static string AddRoleSummary {
            get {
                return ResourceManager.GetString("AddRoleSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuilds boss raid.
        /// </summary>
        public static string AdjustRaidBossSummary {
            get {
                return ResourceManager.GetString("AdjustRaidBossSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It will reset the raid time.
        /// </summary>
        public static string AdjustRaidTimeSummary {
            get {
                return ResourceManager.GetString("AdjustRaidTimeSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Commands.
        /// </summary>
        public static string AllCommands {
            get {
                return ResourceManager.GetString("AllCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available commands.
        /// </summary>
        public static string AvailableCommands {
            get {
                return ResourceManager.GetString("AvailableCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad parameters.
        /// </summary>
        public static string BadParameters {
            get {
                return ResourceManager.GetString("BadParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time is not in valid format.
        /// </summary>
        public static string BadTimeFormat {
            get {
                return ResourceManager.GetString("BadTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Use.
        /// </summary>
        public static string BasicUse {
            get {
                return ResourceManager.GetString("BasicUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boss.
        /// </summary>
        public static string Boss {
            get {
                return ResourceManager.GetString("Boss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the boss..
        /// </summary>
        public static string BossName {
            get {
                return ResourceManager.GetString("BossName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks whether the user has a team set up. If not, he will receive a message with information on how to set it.
        /// </summary>
        public static string CheckTeamSummary {
            get {
                return ResourceManager.GetString("CheckTeamSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        public static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No command found {0}, I couldn&apos;t find it.
        /// </summary>
        public static string CommandNotFound {
            get {
                return ResourceManager.GetString("CommandNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controlled user.
        /// </summary>
        public static string ControlledUser {
            get {
                return ResourceManager.GetString("ControlledUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Level (1-40).
        /// </summary>
        public static string CurrentLevel {
            get {
                return ResourceManager.GetString("CurrentLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date is not in valid format .
        /// </summary>
        public static string DateNotValid {
            get {
                return ResourceManager.GetString("DateNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes all messages (limited).
        /// </summary>
        public static string DeleteAllMessagesSummary {
            get {
                return ResourceManager.GetString("DeleteAllMessagesSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes tagged user messages (limited).
        /// </summary>
        public static string DeleteLastMessageSummary {
            get {
                return ResourceManager.GetString("DeleteLastMessageSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Raid.
        /// </summary>
        public static string DeleteRaidSummary {
            get {
                return ResourceManager.GetString("DeleteRaidSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes your messages (limited).
        /// </summary>
        public static string DeleteYourMessagesSummary {
            get {
                return ResourceManager.GetString("DeleteYourMessagesSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Use.
        /// </summary>
        public static string FullUse {
            get {
                return ResourceManager.GetString("FullUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists help for a specific command.
        /// </summary>
        public static string HelpSummary {
            get {
                return ResourceManager.GetString("HelpSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re in the team.
        /// </summary>
        public static string InTeam {
            get {
                return ResourceManager.GetString("InTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns a link to the Discord invitation here.
        /// </summary>
        public static string InviteSummary {
            get {
                return ResourceManager.GetString("InviteSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists Commands..
        /// </summary>
        public static string ListCommandsSummary {
            get {
                return ResourceManager.GetString("ListCommandsSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Messages.
        /// </summary>
        public static string MessageNumber {
            get {
                return ResourceManager.GetString("MessageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none here.
        /// </summary>
        public static string NoDefaultChannel {
            get {
                return ResourceManager.GetString("NoDefaultChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional, default is.
        /// </summary>
        public static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other players (without Discord, 2nd mobile, etc.).
        /// </summary>
        public static string OtherPlayers {
            get {
                return ResourceManager.GetString("OtherPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Description.
        /// </summary>
        public static string ParameterDescription {
            get {
                return ResourceManager.GetString("ParameterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string Parameters {
            get {
                return ResourceManager.GetString("Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to create a raid in the past?.
        /// </summary>
        public static string PastRaid {
            get {
                return ResourceManager.GetString("PastRaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        public static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You probably play another game ... the allowed level is 1-40.
        /// </summary>
        public static string PlayAnotherGame {
            get {
                return ResourceManager.GetString("PlayAnotherGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        public static string Players {
            get {
                return ResourceManager.GetString("Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only these values ​​are possible.
        /// </summary>
        public static string PossibleValues {
            get {
                return ResourceManager.GetString("PossibleValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists basic boss info.
        /// </summary>
        public static string RaidBossInfoSummary {
            get {
                return ResourceManager.GetString("RaidBossInfoSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raid not found..
        /// </summary>
        public static string RaidNotFound {
            get {
                return ResourceManager.GetString("RaidNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to create a scheduled raid poll from this channel.
        /// </summary>
        public static string RaidNotPossible {
            get {
                return ResourceManager.GetString("RaidNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected team (role).
        /// </summary>
        public static string SelectedTeam {
            get {
                return ResourceManager.GetString("SelectedTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets team and level.
        /// </summary>
        public static string SetBasicInfoSummary {
            get {
                return ResourceManager.GetString("SetBasicInfoSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the level.
        /// </summary>
        public static string SetLevelSummary {
            get {
                return ResourceManager.GetString("SetLevelSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the team.
        /// </summary>
        public static string SetTeamSummary {
            get {
                return ResourceManager.GetString("SetTeamSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a raid poll in a special channel..
        /// </summary>
        public static string StartRaidSummary {
            get {
                return ResourceManager.GetString("StartRaidSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a scheduled raid poll in a special channel.
        /// </summary>
        public static string StartScheduledRaidSummary {
            get {
                return ResourceManager.GetString("StartScheduledRaidSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you would like to support the development, please contact Pako # 3904.
        /// </summary>
        public static string SupportDevelopment {
            get {
                return ResourceManager.GetString("SupportDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input text has too few parameters.
        /// </summary>
        public static string TooFewArgs {
            get {
                return ResourceManager.GetString("TooFewArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input text has too many parameters.
        /// </summary>
        public static string TooManyArgs {
            get {
                return ResourceManager.GetString("TooManyArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where.
        /// </summary>
        public static string Where {
            get {
                return ResourceManager.GetString("Where", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without Team.
        /// </summary>
        public static string WithoutTeam {
            get {
                return ResourceManager.GetString("WithoutTeam", resourceCulture);
            }
        }
    }
}
